# Generated by Django 3.0.7 on 2020-06-17 21:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='', max_length=1000)),
                ('owner', models.CharField(default='', max_length=100)),
                ('startdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('language', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('finishdate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('file', models.FileField(blank=True, upload_to='attachments/')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='app.Project')),
            ],
        ),
    ]
