# Generated by Django 3.0.7 on 2020-06-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200618_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
