# Generated by Django 3.0.7 on 2020-06-20 13:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_project_finished'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('comment', models.TextField(default='', max_length=1000)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
