# Generated by Django 3.0.7 on 2020-06-28 08:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200620_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='archivedate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
